### ISSUE TITLE
TupleViewer does not allow me to see tuples if contextResource and context is specified

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#107] opened 2015-02-26 23:18 UTC
Unsure if this is working as designed...

I originally had this testcase:

	() as Map = HTTPTupleView(In0 as inPort0Alias)
		{
			window
				inPort0Alias : tumbling, count(1) ;
			param
				contextResourceBase : getThisToolkitDir() + "/etc" ;
				context : "map" ;
			config
				placement : partitionColocation("jetty") ;
		}

I expected that the following URL will allow me to see tuples:
http://127.0.0.1:8080/Map/ports/input/0/tuples

But this will always return with an error saying that the URL is not found.  I have to remove the "contextResourceBase" and "context" parameters in order for the aforementioned URL to work.

I have static web pages that I want to publish to Jetty.  But this forces me to have to have two HTTPTupleView operators.  One for serving the static webpage, and another one to allow me to see tuples.

**Comment by hildrum** [comment] 2015-02-27 02:37
As I understand the [documentation](http://ibmstreams.github.io/streamsx.inet/com.ibm.streamsx.inet/doc/spldoc/html/index.html), the URL you'd need with the context argument is: `http://127.0.0.1:8080/map/Map/ports/input/0/tuples`

**Comment by ddebrunner** [comment] 2015-06-03 21:17
@hildrum is correct, the resource base applies to the resource paths provided by the operator, this gives the operator a fixed resource path (/map/Map/ports/input/0/tuples in this case) regardless of how deep in the SPL nesting the operator is.

Closing as working as intended.

**Closed by ddebrunner** 2015-06-03 21:17 UTC
